project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: project_overview.qmd

  
format:
  html:
    toc: true
    smooth-scroll: true
    theme:
      light: material
      dark: darkly